### ISSUE TITLE
HCC Withdrawal from Yobit

### ISSUE THREAD

**Issue by moonmoxie** [healthcarechain/hcc#2]
I am unable to withdraw my coins from the Yobit exchange. This has been an issue since 8-19-2017. I have emailed support as well to no avail. It just says "in process" and no address to track. Please advise

**Comment by healthcarechain** [comment]
what is yobit? we do not list on yobit exchange

**Comment by ghost** [comment]
@moonmoxie HCC on yobit is HAPPY CREATOR COIN. You are on the repo of Health Care Chain
